### ISSUE TITLE
Power button and fingerprint reader can be unresponsive

### ISSUE THREAD

**Issue by brian6932** [arter97/android_kernel_asus_zenfone9#1]
Sometimes it's ok, but a lot of the time you have to try multiple times to get any activation/read. Particularly when holding the power button to get the power menu.

ROM: `omni-14-202403121645-zenfone9-GAPPS`

**Comment by brian6932** [comment]
I'm still exhibiting this issue on `r6`, it feels like there's some cooldown on button usage, so maybe it's not strictly random, but it's been a while since I last tried `r5`, so I'll update this post if there's any other info. I'm currently on `omni-14-202408061727-zenfone9-GAPPS` ROM.

**Comment by arter97** [comment]
Try r7.

**Comment by brian6932** [comment]
Fixed.
