### ISSUE TITLE
Crashing apps due to inaccessibility of their own `/sdcard/Android/data/<package name>` dirs

### ISSUE THREAD

**Issue by brian6932** [arter97/android_kernel_asus_zenfone9#4]
For some reason lots of apps are complaining about a lack of access to their own `/sdcard/Android/data/<package name>` dirs, after updating to `omni-14-202403121645-zenfone9-GAPPS`. This causes tons of crashes, and logs within logcat. Deleting the dirs, clearing the app data, and reinstalling the apps, all don't work. I'm not sure if the `/data/data/<package name>` dir's are also effected by this.
The stock boot.img doesn't exhibit this, neither does a stock boot.img + a KernelSU AnyKernel flash.

**Comment by arter97** [comment]
Only stock firmware is supported. If you encounter these issues on the stock firmware, please report it in the XDA forum thread or Telegram group chat.

**Comment by brian6932** [comment]
Fixed in `r6`.
